######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 13 21:35:42 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += circles.h MyGraphicsView.h team.h
SOURCES += circles.cpp main.cpp MyGraphicsView.cpp team.cpp
